Web/Pages/Admin/Blogs/Add.cshtml.cs
using Application.Models;
using Application.Models.Enums;
using Application.Services.Interfaces;
using AutoMapper;
using Domain.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Text.Json;

namespace Web.Pages.Admin.Blogs
{
    [Authorize(Roles = "Admin")]
    public class AddModel : PageModel
    {
        private readonly IBlogPostService _blogPostService;
        private readonly IMapper _mapper;

        [BindProperty]
        public AddBlogPostModel AddBlogPostModel { get; set; } = new AddBlogPostModel() { PublishedDate = DateTime.UtcNow.Date };

        [BindProperty]
        public IFormFile FeaturedImage { get; set; }

        [BindProperty]
        public string Tags { get; set; }

        public AddModel(IBlogPostService blogPostService, IMapper mapper)
        {
            _blogPostService = blogPostService;
            _mapper = mapper;
        }

        public void OnGet()
        {
            var a = User.Identity.Name;
        }

        public async Task<ActionResult> OnPostAsync()
        {
            if (!string.IsNullOrWhiteSpace(Tags))
            {
                var tags = JsonSerializer.Deserialize<List<TagInputModel>>(Tags);
                AddBlogPostModel.Tags = _mapper.Map<List<Tag>>(tags);
            }

            var response = await _blogPostService.AddBlogPost(AddBlogPostModel);

            ModelState.Clear();

            if (response.ValidationErrors.Any())
            {
                foreach (var error in response.ValidationErrors)
                {
                    ModelState.AddModelError("AddBlogPostModel." + error.Property, error.Message);
                }
            }

            if (response.AlertType != MessageAlertType.None)
            {
                TempData["Alert"] = AlertModel.GetJsonString(response.Message, response.AlertType);
            }

            if (response.Success)
            {
                return RedirectToPage("/Admin/Blogs/List");
            }

            return Page();
        }
    }
}

Web/Pages/Admin/Blogs/Edit.cshtml.cs
using Application.Models;
using Application.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Application.Models.Enums;
using System;
using Domain.Entities;
using Microsoft.AspNetCore.Authorization;
using System.Text.Json;
using AutoMapper;

namespace Web.Pages.Admin.Blogs
{
    [Authorize(Roles = "Admin")]
    public class EditModel : PageModel
    {
        private readonly IBlogPostService _blogPostService;
        private readonly IMapper _mapper;

        [BindProperty]
        public EditBlogPostModel EditBlogPostModel { get; set; }

        [BindProperty]
        public IFormFile FeaturedImage { get; set; }

        [BindProperty]
        public string Tags { get; set; }

        public EditModel(IBlogPostService blogPostService, IMapper mapper)
        {
            _blogPostService = blogPostService;
            _mapper = mapper;
        }

        public async Task<IActionResult> OnGetAsync(Guid id)
        {
            var response = await _blogPostService.GetBlogPostToEdit(id);

            if (response.AlertType != MessageAlertType.None)
            {
                TempData["Alert"] = AlertModel.GetJsonString(response.Message, response.AlertType);
            }

            if (response.Success)
            {
                EditBlogPostModel = response.Data;

                if (EditBlogPostModel.Tags != null && EditBlogPostModel.Tags.Any())
                {
                    Tags = string.Join(',', EditBlogPostModel.Tags.Select(x => x.Name));
                }

                return Page();
            }

            return RedirectToPage("/Admin/Blogs/List");
        }

        public async Task<IActionResult> OnPostEdit()
        {
            if (!string.IsNullOrWhiteSpace(Tags))
            {
                var tags = JsonSerializer.Deserialize<List<TagInputModel>>(Tags);
                EditBlogPostModel.Tags = _mapper.Map<List<Tag>>(tags);
            }

            var response = await _blogPostService.EditBlogPost(EditBlogPostModel);

            ModelState.Clear();

            if (response.ValidationErrors.Any())
            {
                foreach (var error in response.ValidationErrors)
                {
                    ModelState.AddModelError("EditBlogPostModel." + error.Property, error.Message);
                }
            }

            if (response.AlertType != MessageAlertType.None)
            {
                TempData["Alert"] = AlertModel.GetJsonString(response.Message, response.AlertType);
            }

            return Page();
        }

        public async Task<IActionResult> OnPostDelete()
        {
            var response = await _blogPostService.DeleteBlogPost(EditBlogPostModel.Id);

            if (response.AlertType != MessageAlertType.None)
            {
                TempData["Alert"] = AlertModel.GetJsonString(response.Message, response.AlertType);
            }

            return RedirectToPage("/Admin/Blogs/List");
        }
    }
}

Web/Pages/Admin/Blogs/List.cshtml.cs
using Application.Models;
using Application.Models.Enums;
using Application.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Text.Json;

namespace Web.Pages.Admin.Blogs
{
    [Authorize(Roles = "Admin")]
    public class ListModel : PageModel
    {
        private readonly IBlogPostService _blogPostService;

        [BindProperty]
        public List<ListBlogPostModel> ListBlogPostModels { get; set; }

        public ListModel(IBlogPostService blogPostService)
        {
            _blogPostService = blogPostService;
        }

        public async Task<IActionResult> OnGetAsync()
        {
            var response = await _blogPostService.GetAllBlogPosts();

            if (response.AlertType != MessageAlertType.None)
            {
                TempData["Alert"] = AlertModel.GetJsonString(response.Message, response.AlertType);
            }

            if (response.Success)
            {
                ListBlogPostModels = response.Data;
            }

            return Page();
        }
    }
}

Web/Pages/Blog/Details.cshtml.cs
using Application.Models;
using Application.Models.Enums;
using Application.Services.Interfaces;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Web.Pages.Blog
{
    public class DetailsModel : PageModel
    {
        private readonly IBlogPostService _blogPostService;
        private readonly IBlogPostLikeService _blogPostLikeService;
        private readonly IBlogPostCommentService _blogPostCommentService;
        private readonly UserManager<IdentityUser> _userManager;

        [BindProperty]
        public AddBlogPostCommentModel Comment { get; set; }
        [BindProperty]
        public Guid BlogPostId { get; set; }

        public List<BlogPostCommentOnList> Comments { get; set; }

        public DetailsBlogPostModel BlogPost { get; set; }

        public int LikesCount { get; set; }
        public bool Liked { get; set; }

        public DetailsModel(IBlogPostService blogPostService, IBlogPostLikeService blogPostLikeService, IBlogPostCommentService blogPostCommentService, UserManager<IdentityUser> userManager)
        {
            _blogPostService = blogPostService;
            _blogPostLikeService = blogPostLikeService;
            _blogPostCommentService = blogPostCommentService;
            _userManager = userManager;
        }

        public async Task<IActionResult> OnGetAsync(string urlHandle)
        {
            var response = await _blogPostService.GetBlogPostDetails(urlHandle);

            if (response.AlertType != MessageAlertType.None)
            {
                TempData["Alert"] = AlertModel.GetJsonString(response.Message, response.AlertType);
            }

            if (response.Success)
            {
                BlogPost = response.Data;
                BlogPostId = BlogPost.Id;

                var likesResponse = await _blogPostLikeService.GetLikesCountByBlogPostId(response.Data.Id);

                LikesCount = likesResponse.Data;

                var userId = _userManager.GetUserId(User);

                if (!string.IsNullOrWhiteSpace(userId))
                {
                    var likedResponse = await _blogPostLikeService.CheckUserLiked(response.Data.Id, Guid.Parse(userId));
                    Liked = likedResponse.Data;
                }

                var commentResponse = await _blogPostCommentService.GetCommentsByPost(BlogPostId);

                if (commentResponse.Success)
                {
                    Comments = commentResponse.Data;
                }

                return Page();
            }

            return RedirectToPage("/Index");
        }

        public async Task<IActionResult> OnPostAsync(string urlHandle)
        {
            var userId = _userManager.GetUserId(User);

            Comment.BlogPostId = BlogPostId;
            Comment.UserId = Guid.Parse(userId);

            var response = await _blogPostCommentService.AddComment(Comment);

            if (response.AlertType != MessageAlertType.None)
            {
                TempData["Alert"] = AlertModel.GetJsonString(response.Message, response.AlertType);
            }

            return RedirectToPage("/blog/Details", new { urlHandle = urlHandle });
        }
    }
}

Web/Pages/Admin/Blogs/Add.cshtml
@page
@model Web.Pages.Admin.Blogs.AddModel
@{
}

<div class="bg-secondary bg-opacity-10 py-2 mb-5">
    <div class="container">
        <h1>Add Blog Post</h1>
    </div>
</div>

<partial name="_Alert" />

<div>
    <div class="container">
        <form method="post">
            <div class="form-group mb-3">
                <label for="heading">Heading</label>
                <input type="text" class="form-control" id="heading" asp-for="AddBlogPostModel.Heading">
                <span asp-validation-for="AddBlogPostModel.Heading" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label for="pageTitle">Page Title</label>
                <input type="text" class="form-control" id="pageTitle" asp-for="AddBlogPostModel.PageTitle">
                <span asp-validation-for="AddBlogPostModel.PageTitle" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label for="content">Content</label>
                <textarea class="form-control" id="content" asp-for="AddBlogPostModel.Content"></textarea>
                <span asp-validation-for="AddBlogPostModel.Content" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label for="shortDescription">Short Description</label>
                <input type="text" class="form-control" id="shortDescription" asp-for="AddBlogPostModel.ShortDescription">
                <span asp-validation-for="AddBlogPostModel.ShortDescription" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label for="featuredImageUpload">Featured Image Upload</label>
                <input type="file" class="form-control" id="featuredImageUpload" asp-for="FeaturedImage" />
                <img class="py-2" src="" id="featuredImageDisplay" style="display:none; width: 300px;" />
            </div>

            <div class="form-group mb-3">
                <label for="featuredImageUrl">Featured Image Url</label>
                <input type="text" class="form-control" id="featuredImageUrl" asp-for="AddBlogPostModel.FeaturedImageUrl">
                <span asp-validation-for="AddBlogPostModel.FeaturedImageUrl" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label for="urlHandle">Url Handle</label>
                <input type="text" class="form-control" id="urlHandle" asp-for="AddBlogPostModel.UrlHandle">
                <span asp-validation-for="AddBlogPostModel.UrlHandle" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label for="publishedDate">Published Date</label>
                <input type="date" class="form-control" id="publishedDate" asp-for="AddBlogPostModel.PublishedDate">
                <span asp-validation-for="AddBlogPostModel.PublishedDate" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label for="author">Author</label>
                <input type="text" class="form-control" id="author" asp-for="AddBlogPostModel.Author">
                <span asp-validation-for="AddBlogPostModel.Author" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label for="tags" class="form-label">Tags (comma separated)</label>
                <input type="text" class="form-control text-uppercase" id="tags" asp-for="Tags" />
            </div>

            <div class="form-check mb-3">
                <input type="checkbox" class="form-check-input" id="visible" asp-for="AddBlogPostModel.Visible">
                <label class="form-check-label" for="visible">Visible</label>
            </div>

            <div class="mb-3">
                <button class="btn btn-primary" type="submit">Add</button>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <script>
        const featuredImageUploadElement = document.getElementById('featuredImageUpload');
        const featuredImageUrl = document.getElementById('featuredImageUrl');
        const featuredImageDisplay = document.getElementById('featuredImageDisplay');
        const tagsInput = document.getElementById('tags');

        new Tagify(tagsInput);

        var editor = new FroalaEditor('#content', {
            imageUploadURL: '/api/images',
            imageUploadMethod: 'POST',
            events: {
                'image.uploaded': function (response) {
                    var parsedResponse = JSON.parse(response);

                    var imageUrl = parsedResponse.data;


                    this.image.insert(imageUrl, false, null, this.image.get(), response);

                    return false;
                }
            }
        });


        async function uploadFeaturedImage(e) {
            let data = new FormData();
            data.append('file', e.target.files[0]);

            await fetch('/api/images', {
                method: 'POST',
                headers: {
                    'Accept': '*/*',
                },
                body: data
            }).then(response => response.json())
                .then(result => {
                    if (result.success == true)
                    {
                        featuredImageUrl.value = result.data;
                        featuredImageDisplay.style.display = 'block';
                        featuredImageDisplay.src = result.data;
                    }
                });
        }

        featuredImageUploadElement.addEventListener('change', uploadFeaturedImage);
    </script>
}

Web/Pages/Admin/Blogs/Edit.cshtml
@page "{id:Guid}"
@model Web.Pages.Admin.Blogs.EditModel
@{
}

<div class="bg-secondary bg-opacity-10 py-2 mb-5">
    <div class="container">
        <h1>Edit Blog Post</h1>
    </div>
</div>

<partial name="_Alert" />

<div>
    <div class="container">
        <form method="post">
            <input type="hidden" asp-for="EditBlogPostModel.Id">

            <div class="form-group mb-3">
                <label for="heading">Heading</label>
                <input type="text" class="form-control" id="heading" asp-for="EditBlogPostModel.Heading">
                <span asp-validation-for="EditBlogPostModel.Heading" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label for="pageTitle">Page Title</label>
                <input type="text" class="form-control" id="pageTitle" asp-for="EditBlogPostModel.PageTitle">
                <span asp-validation-for="EditBlogPostModel.PageTitle" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label for="content">Content</label>
                <textarea class="form-control" id="content" asp-for="EditBlogPostModel.Content"></textarea>
                <span asp-validation-for="EditBlogPostModel.Content" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label for="shortDescription">Short Description</label>
                <input type="text" class="form-control" id="shortDescription" asp-for="EditBlogPostModel.ShortDescription">
                <span asp-validation-for="EditBlogPostModel.ShortDescription" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label for="featuredImageUpload">Featured Image Upload</label>
                <input type="file" class="form-control" id="featuredImageUpload" asp-for="FeaturedImage" />
                @if (Model.EditBlogPostModel.FeaturedImageUrl != null)
                {
                    <img class="py-2" src="@Model.EditBlogPostModel.FeaturedImageUrl" id="featuredImageDisplay" style="width: 300px;" />
                }
                else
                {
                    <img class="py-2" src="" id="featuredImageDisplay" style="display:none; width: 300px;" />
                }
            </div>

            <div class="form-group mb-3">
                <label for="featuredImageUrl">Featured Image Url</label>
                <input type="text" class="form-control" id="featuredImageUrl" asp-for="EditBlogPostModel.FeaturedImageUrl">
                <span asp-validation-for="EditBlogPostModel.FeaturedImageUrl" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label for="urlHandle">Url Handle</label>
                <input type="text" class="form-control" id="urlHandle" asp-for="EditBlogPostModel.UrlHandle">
                <span asp-validation-for="EditBlogPostModel.UrlHandle" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label for="publishedDate">Published Date</label>
                <input type="date" class="form-control" id="publishedDate" asp-for="EditBlogPostModel.PublishedDate">
                <span asp-validation-for="EditBlogPostModel.PublishedDate" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label for="author">Author</label>
                <input type="text" class="form-control" id="author" asp-for="EditBlogPostModel.Author">
                <span asp-validation-for="EditBlogPostModel.Author" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label for="tags" class="form-label">Tags (comma separated)</label>
                <input type="text" class="form-control text-uppercase" id="tags" asp-for="Tags" />
            </div>

            <div class="form-check mb-3">
                <input type="checkbox" class="form-check-input" id="visible" asp-for="EditBlogPostModel.Visible">
                <label class="form-check-label" for="visible">Visible</label>
            </div>

            <div class="mb-3 d-flex justify-content-between">
                <button class="btn btn-primary" type="submit" asp-page-handler="Edit">Save</button>
                <button class="btn btn-danger" type="submit" asp-page-handler="Delete">Delete</button>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <script>
        const featuredImageUploadElement = document.getElementById('featuredImageUpload');
        const featuredImageUrl = document.getElementById('featuredImageUrl');
        const featuredImageDisplay = document.getElementById('featuredImageDisplay');
        const tagsInput = document.getElementById('tags');

        new Tagify(tagsInput);

        var editor = new FroalaEditor('#content', {
            imageUploadURL: '/api/images',
            imageUploadMethod: 'POST',
            events: {
                'image.uploaded': function (response) {
                    var parsedResponse = JSON.parse(response);

                    var imageUrl = parsedResponse.data;


                    this.image.insert(imageUrl, false, null, this.image.get(), response);

                    return false;
                }
            }
        });


        async function uploadFeaturedImage(e) {
            let data = new FormData();
            data.append('file', e.target.files[0]);

            await fetch('/api/images', {
                method: 'POST',
                headers: {
                    'Accept': '*/*',
                },
                body: data
            }).then(response => response.json())
                .then(result => {
                    if (result.success == true) {
                        featuredImageUrl.value = result.data;
                        featuredImageDisplay.style.display = 'block';
                        featuredImageDisplay.src = result.data;
                    }
                });
        }

        featuredImageUploadElement.addEventListener('change', uploadFeaturedImage);
    </script>
}

Web/Pages/Admin/Blogs/List.cshtml
@page
@model Web.Pages.Admin.Blogs.ListModel
@{
}

<div class="bg-secondary bg-opacity-10 py-2 mb-5">
    <div class="container">
        <h1>Blog Posts</h1>
    </div>
</div>

<partial name="_Alert" />

@if (Model.ListBlogPostModels != null && Model.ListBlogPostModels.Any())
{
    <div>
        <div class="container">
            <table class="table">
                <thead>
                    <tr>
                        <td>Id</td>
                        <td>Heading</td>
                        <td>Visible</td>
                        <td></td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var blogPost in Model.ListBlogPostModels)
                    {
                        <tr>
                            <td>@blogPost.Id</td>
                            <td>@blogPost.Heading</td>
                            <td>
                                @if (blogPost.Visible)
                                {
                                    <span>✓</span>
                                }
                            </td>
                            <td><a href="/Admin/Blogs/Edit/@blogPost.Id">View</a></td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
}